### ISSUE TITLE
Error installing package

### ISSUE THREAD

**Issue by karneaud** [bguiz/modernizr-cli#3]
> npm ERR! Command failed: git clone --template=/Users/kendallarneaud/.npm/_git-remotes/_templates --mirror ssh://git@github.com/Modernizr/Modernizr.git /Users/kendallarneaud/.npm/_git-remotes/ssh-git-github-com-Modernizr-Modernizr-git-74113f5b
> npm ERR! Cloning into bare repository '/Users/kendallarneaud/.npm/_git-remotes/ssh-git-github-com-Modernizr-Modernizr-git-74113f5b'...
> npm ERR! Permission denied (publickey).
> npm ERR! fatal: Could not read from remote repository.
> npm ERR! 
> npm ERR! Please make sure you have the correct access rights
> npm ERR! and the repository exists.
> npm ERR! 
> npm ERR! 
> npm ERR! If you need help, you may report this error at:
> npm ERR!     https://github.com/npm/npm/issues

**Comment by bguiz** [comment]
You'll need to set up SSH access for github.

W: http://bguiz.com

**Comment by karneaud** [comment]
smh...good grief couldn't this be any simpler

**Comment by bguiz** [comment]
FYI, for future reference while it isn't required for all packages,
sometimes dependencies are defined as git repos, and you will need to
configure SSH access for that git repo.

Whenever you see

```
npm ERR! Cloning into bare repository
```

followed by

```
npm ERR! Permission denied (publickey).
```

it most likely means that npm tried to clone a dependency from a git
repo, but failed because SSH authentication failed.

W: http://bguiz.com
